### ISSUE TITLE
AccessToken from Refresh Token

### ISSUE THREAD

**Issue by Rishabhk07** [jaebradley/tinder-access-token-generator#18]
Hey, great work on the library, but since the library already fetches the refresh token, can we include a function to get access token from refreshToken?

**Comment by jaebradley** [comment]
@Rishabhk07 yeah definitely - I haven't found any explicit documentation on using a refresh token to get a new access token but I assume it's pretty similar to one of a couple OAuth standards.

**Comment by Rishabhk07** [comment]
yeah. It should be, I am also "identifying" the API :P and if I came around anything, I will write it and generate a PR. Thank you again, you have done some pretty amazing work with this
