### ISSUE TITLE
Running as root without --no-sandow is not supported

### ISSUE THREAD

**Issue by jussetain** [jaebradley/tinder-access-token-generator#24]
Hi, nice job for this package, though, when I try to push this on a remote debian server and run it as root, puppeteer throws an error : 

```
Error: Failed to launch chrome!
[0725/012220.612629:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

Any idea ?
Thanks.

**Comment by jaebradley** [comment]
@jussetain have you taken a look at [`puppeteer`'s steps for setting up on linux](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox)? Is there a way you can modify your existing workflow to not execute running logic related to this package as `root`?

If not, I think one thing I can do on my end is allow `generateAccessToken` to take a puppeteer configuration object to be used by the underlying call to [`puppeteer.launch`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox).

**Comment by Istani** [comment]
@jaebradley i have the same issue myself with running "docker toolbox for windows" (perhaps other dockers too)...

i used https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker but that doesnt allow me to use volumes for my app Code...

Well i changed it myself in the node_modules folder...

But maybe you want to add something for docker in your readme ?

**Comment by jaebradley** [comment]
@Istani thanks for confirming the behavior - I can definitely add something to the `README`.

**Comment by Istani** [comment]
Yeah i only got it working with this Dockerfile https://raw.githubusercontent.com/Istani/Node_TinderAutomation/master/Dockerfile and changing the files in this dictonary node_modules/tinder-access-token-generator/build/

But i guess there are better ways to do it...
